### PR TITLE
update OpenSeadragon to 2.1.0

### PR DESCRIPTION
**Pull request by ebenenglish**
This PR simply updates the source Openseadragon JS code to version 2.1.0.

### CODE REVIEW

**Comment by ebenenglish** [comment]
Not sure what's going on with these 2 failing specs, both give the same error. Sprockets issue, obviously, but I was unable to successfully diagnose this.

```
Failures:

  1) Openseadragon::OpenseadragonHelper#osd_asset_defaults ['prefixUrl'] 
     Failure/Error: let(:defaults) { helper.send(:osd_asset_defaults) }
     Sprockets::FileNotFound:
       couldn't find file 'jquery' with type 'application/javascript'
     # ./spec/internal/app/assets/javascripts/application.js:13
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/resolve.rb:64:in `resolve!'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/directive_processor.rb:399:in `resolve'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/directive_processor.rb:207:in `process_require_directive'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/directive_processor.rb:178:in `each'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/directive_processor.rb:178:in `process_directives'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/directive_processor.rb:83:in `_call'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/directive_processor.rb:68:in `call'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/loader.rb:60:in `block in load'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/loader.rb:44:in `load'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `yield'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `load'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/bundle.rb:23:in `block in call'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/utils.rb:183:in `dfs'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/bundle.rb:24:in `call'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/loader.rb:60:in `block in load'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/loader.rb:44:in `load'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `yield'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `load'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/base.rb:66:in `find_asset'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:142:in `block in find'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:225:in `block in stat_tree'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:209:in `block in stat_directory'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `each'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `stat_directory'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:224:in `stat_tree'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:105:in `each'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:104:in `each'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:104:in `logical_paths'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:140:in `find'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:49:in `each'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:49:in `map'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:49:in `precompiled_assets'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:34:in `asset_precompiled?'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:214:in `block (3 levels) in <class:Railtie>'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:345:in `call'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:345:in `precompiled?'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:349:in `raise_unless_precompiled_asset'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:323:in `digest_path'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:311:in `asset_path'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:89:in `block in resolve_asset_path'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:229:in `block in resolve_asset'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:228:in `each'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:228:in `detect'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:228:in `resolve_asset'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:88:in `resolve_asset_path'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:78:in `compute_asset_path'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/actionview-4.2.4/lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
     # /home/eenglish/.rvm/gems/ruby-2.2.1/gems/actionview-4.2.4/lib/action_view/helpers/asset_url_helper.rb:292:in `image_path'
     # ./app/helpers/openseadragon/openseadragon_helper.rb:127:in `osd_asset_defaults'
     # ./spec/helpers/openseadragon_helper_spec.rb:104:in `block (3 levels) in <top (required)>'
     # ./spec/helpers/openseadragon_helper_spec.rb:107:in `block (4 levels) in <top (required)>'
     # ./spec/helpers/openseadragon_helper_spec.rb:108:in `block (4 levels) in <top (required)>'
```

**Comment by ebenenglish** [comment]
Only the Ruby 1.9.3 build is failing, because of this error:
```
Gem::InstallError: mime-types-data requires Ruby version >= 2.0.
```
Looks like there are some ways to [patch](https://github.com/travis-ci/travis-ci/issues/5145) this, but do we still care about 1.9.3? Seems like most of the other Blacklight projects don't support this any more.

**Comment by cbeer** [comment]
Sounds good -- I see no reason to require 1.9.3 any more.

**Comment by ebenenglish** [comment]
@cbeer do we want to integrate removing support for 1.9.3 into this PR, or should it be a separate PR? (FYI, we'll need the commits from https://github.com/IIIF/openseadragon-rails/pull/15/commits/fb056ce82ab0452c5c14a71f39afdc3f9c14485b in order for the 2.1.0 and 2.0.0 builds/specs to pass.)

**Comment by cbeer** [comment]
Same PR, different commit is fine with me.

**Comment by ebenenglish** [comment]
OK, done. Can we cut a new version of the gem once this PR is merged?

**Comment by ebenenglish** [comment]
@cbeer Any chance we can release a new version of this gem to reflect the updated OSd source? Thanks!

**Pull request merged**
